# Generated by Django 4.2.1 on 2023-06-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                related_name="film_director", to="movies.actor", verbose_name="режиссер"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
                verbose_name="фильм",
            ),
        ),
    ]
