# Generated by Django 4.2.1 on 2023-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_directors_alter_rating_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="трейлер"),
        ),
    ]
